### ISSUE TITLE
New room, M>T comes from bot, when should from puppet

### ISSUE THREAD

**Issue by olmari** [mautrix/telegram#367]
### Issue:

Newly bridged groupchat, made by double-puppetet user (matrix-login), Matrix to Telegram messages comes from relaybot instead puppeted user. No sync commands nor cache clears resolved this, but restarting of bridge did magically corrected it, so some form of "state of things" discrepancy somewhere I suspect. Nothing suspicious observed on either Synapse nor Mautrix-telegarm logs. Also saying something with real Telegram client resulted in correct behaviour (matrix-puppet saying things in room).

### Flow that I happened to use, should any part of it affect somehow:

- Made Matrix room
- Made Telegram group
- Invited some TG users on TG side
- Invited bot both sides
- Executed bridging commands
- Upgraded room to supergroup through bot command
- Talked and observed this behaviour

Bridge version: https://github.com/tulir/mautrix-telegram/commit/d5470de8fd88a01e769197905eace3740ca0ed34

**Comment by Craeckie** [comment]
I just encountered the same issue on current master: 78fcacf7aa5bb97a85df4b8dcabf34bd7e54c686

My flow was a little different:
- Made encrypted Matrix Room
- Added bridge bot
- Added relay bot
- Created TG chat by sending `!tg create`
- Added another TG user
- Sent a message in Matrix
-> The message was forwarded by the relay bot, even though puppeting is enabled and normally works

Restarting the bridge also fixed it for this room.

**Comment by Steffo99** [comment]
Seems like this bug resurfaced again.

When the relay bot is in a group, messages are always sent through it, even when users are puppetted.

![A screenshot of the bug on Telegram](https://user-images.githubusercontent.com/1540885/226832166-1378a415-c9eb-4030-ab92-ec52478d2507.jpg)

![A screenshot of the chat on FluffyChat](https://user-images.githubusercontent.com/1540885/226832494-550c11b9-40b7-4a25-b1bd-2afad525a399.jpg)

Restarts ***do not*** fix the problem anymore, which leads me to think that the problem is somewhere in the code.

I could work on a pull request, but I need to know where this behavior is handled in the code, as I didn't find it on my own.

**Comment by maltee1** [comment]
Uh, for me, restarts or a simple `!tg sync` does still fix the issue.
