### ISSUE TITLE
Profile picture won't get removed

### ISSUE THREAD

**Issue by MaximilianGaedig** [mautrix/telegram#667]
The profile picture in matrix from a bridged user is not getting removed if it is removed on telegram, it just stays the same.

**Comment by tulir** [comment]
This is expected.

* Telegram doesn't tell anyone when avatars are changed or removed, so removals can't be bridged in real time
* There's no reliable way to check if the avatar has been removed, because avatars hidden from you are indistinguishable from no avatar at all. If the bridge had two logged in users and one of them had permissions to see the avatar, the bridge would get confused (similar to different contact list names for the same person), so the solution is to never remove avatars.

**Comment by omginput** [comment]
How to manually remove the profile picture of someone as an admin then?
