### ISSUE TITLE
How to remove kick permissions from the bridge bot?

### ISSUE THREAD

**Issue by moeik** [mautrix/telegram#787]
Please describe the operation steps, thanks.

**Comment by DoumeDuSud** [comment]
@moeik if its in order to be able to bridge public channel to matrix room, and in this room to want matrix only user can join without been kick off by the bot, this is my workaround

- On Telegram transfer a message from the channel you want to bridge to bot : `@JsonDumpBot`
- It's will reply with json output where you will found something like that : 
```
    "date": 1649885228,
    "forward_from_chat": {
      "id": -1001316533036,
      "title": "__D i X i T__",
      "username": "dixitcanal",
      "type": "channel"
    },
```

- Create a room in matrix and invite the Telegram Matrix bot
- made it moderator 
- in room permission remove the right for moderator to kick out user
- bridge the room with telegram channel `!tg bridge -1001316533036`

it's fast to make it and working properly
