### ISSUE TITLE
Own telegram messages forwarded through matrix don't appear on telegram

### ISSUE THREAD

**Issue by JuniorJPDJ** [mautrix/telegram#814]
This is regression in latest forwards feature.
Message first got sent from telegram and bridged to matrix. Then using forward feature in element made message appear on matrix but bridge didn't forward it to telegram.

Telegram side:
![image](https://user-images.githubusercontent.com/7334549/178150587-9936daed-bc75-41e2-9aa2-723ca75e058d.png)

Matrix side:
![image](https://user-images.githubusercontent.com/7334549/178150599-681226af-335c-404b-8b37-97e052619091.png)

Log on INFO level is clean, I'll try on TRACE level.

**Comment by tulir** [comment]
This isn't related to the new forward feature and it's always been like that.

Double puppeted messages won't be bridged when the event content is copied directly, since the bridge treats them as messages that were bridged from Telegram and shouldn't be bridged back (`"fi.mau.double_puppet_source": "mautrix-telegram"` is the relevant part of the event content - modify your client to strip that if you want to forward your own messages).
